os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "4.2.1"
jdk:
  - oraclejdk8
env:
  global:
  - JHIPSTER_MVN_DEP=1
  - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
  - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
  - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
  - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
  matrix:
  - JHIPSTER=app-default
before_install:
  - chmod +x $JHIPSTER_INSTALL/02-install-jhipster-stack.sh
  - chmod +x $JHIPSTER_INSTALL/02-downloadDep.sh
  - chmod +x $JHIPSTER_INSTALL/02-checkVersion.sh
install:
  - $JHIPSTER_INSTALL/02-install-jhipster-stack.sh
  - $JHIPSTER_INSTALL/03-downloadDep.sh
  - $JHIPSTER_INSTALL/04-checkVersion.sh
script:
  - $JHIPSTER_SCRIPTS/01-generate-project.sh
  - $JHIPSTER_SCRIPTS/02-generate-entities.sh
